server:
    port: 8761
#Eureka的保护机制 不建议
#    enable-self-presservation: false
eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
